# Generated by Django 2.2.6 on 2019-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.AutoField(primary_key=True, serialize=False)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
            ],
        ),
    ]
