# Generated by Django 2.2.6 on 2019-10-23 18:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blueberry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employerid', models.AutoField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='site',
            old_name='zipcode',
            new_name='zip_code',
        ),
        migrations.CreateModel(
            name='WagePosting',
            fields=[
                ('postingid', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=256)),
                ('wage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField()),
                ('employerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueberry.Employer')),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueberry.Site')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WageBuffer',
            fields=[
                ('postingid', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=256)),
                ('wage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField()),
                ('employerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueberry.Employer')),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueberry.Site')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HousingPosting',
            fields=[
                ('postingid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField()),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueberry.Site')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HousingBuffer',
            fields=[
                ('postingid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.IntegerField()),
                ('siteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueberry.Site')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
