# Generated by Django 2.2.6 on 2019-10-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blueberry', '0002_auto_20191023_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingposting',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting', to='blueberry.Site'),
        ),
    ]
