# Generated by Django 2.2.6 on 2019-10-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueberry', '0004_album_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RenameField(
            model_name='housingbuffer',
            old_name='siteid',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='housingposting',
            old_name='siteid',
            new_name='site',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
