# Generated by Django 2.2.6 on 2019-10-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blueberry', '0005_auto_20191024_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingbuffer',
            old_name='site',
            new_name='siteid',
        ),
        migrations.RemoveField(
            model_name='housingposting',
            name='site',
        ),
        migrations.AddField(
            model_name='housingposting',
            name='siteid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='housingposting', to='blueberry.Site'),
            preserve_default=False,
        ),
    ]
