# Generated by Django 2.2.6 on 2019-10-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blueberry', '0006_auto_20191024_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageposting',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wageposting', to='blueberry.Site'),
        ),
    ]
